#!/bin/sh

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac


. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/lib/udev/rules.d/
for rule in /etc/udev/rules.d/*; do 
    cp -p $rule ${DESTDIR}/lib/udev/rules.d/
done;