#!/bin/sh

PREREQ="udev"
EXCEPT_DEVLIST=$(/sbin/blkid -o device -t TYPE=crypto_LUKS)

prereqs()
{
    echo "$PREREQ"
}

case $1 in
    # get pre-requisites
    prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

get_key_from_fs()
{
    mpoint="/flash"
    mkdir -p $mpoint

    wait_for_udev 10
    for dev in $(/sbin/blkid -o device); do
        if [ -z "$(echo -e "$EXCEPT_DEVLIST" | sed -n "\#^$dev\$#p")" ]; then
            EXCEPT_DEVLIST="$EXCEPT_DEVLIST\n$dev"

            FSTYPE=$(/sbin/blkid -o value -s TYPE $dev);
            if mount -o ro -t $FSTYPE $dev $mpoint >/dev/null 2>&1; then
                if [ -s "$mpoint/$MYKEY" ]; then
                    cat "$mpoint/$MYKEY" > "$KEYFILE"
                fi
                umount $dev >/dev/null 2>&1
            fi;
        fi;
        if [ -s "$KEYFILE" ]; then
            return 0
        fi;
    done;
    return 1
}

set_dns()
{
    resolv_conf=/etc/resolv.conf
    rm -f $resolv_conf
    for ns in $DNS; do
	echo "nameserver $ns" >> $resolv_conf
    done;
    if [ -n "$IPV4DNS0" ]; then
	[ "$IPv4DNS0" != "0.0.0.0" ] && echo "nameserver $IPV4DNS0" >> $resolv_conf
    fi
    if [ -n "$IPV4DNS1" ]; then
	[ "$IPv4DNS1" != "0.0.0.0" ] && echo "nameserver $IPV4DNS1" >> $resolv_conf
    fi
}

get_key_from_net()
{
    configure_networking && set_dns
    wait_for_udev 10
    if [ ! -s "$KEYFILE" ]; then
        /sbin/ssh -q -o StrictHostKeyChecking=no -o ConnectTimeout=10 $USERSERV "cat ~/$MYKEY" > "$KEYFILE"
    fi
    if [ -s "$KEYFILE" ]; then
	return 0
    fi;
    return 1;
}

get_key()
{
    get_key_from_fs && return 0
    get_key_from_net && return 0
    return 1
}

main()
{
    while ! get_key; do
	sleep 10;
    done;
}

main


